import Head from "next/head";
// import Image from "next/image"; https://api.chucknorris.io/jokes/categories
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Layout from "./layout";
import { GetServerSideProps } from "next";

export const getServerSideProps: GetServerSideProps = async (context) => {
  const response = await fetch("https://api.chucknorris.io/jokes/categories");
  const categories = await response.json();
  // console.log(categories);
  return {
    props: {
      categories: categories,
    },
  };
};

export default function Home({ categories }) {
  return (
    <div className={styles.container}>
      <Layout>
        <Head>
          <title>Dynamic routing next app</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <nav> </nav>
        </Head>
        <main className={styles.main}>
          <h1 className={styles.title}>Dynamic routing</h1>
          <br />
          <p className={styles.description}>
            Bienvenue sur la page web consacré au travail sur : Dynamic routing
            next app.
            <code className={styles.code}></code>
          </p>
          <div>
            <p>Categories of joke :</p>
            <p>
              {categories.map((element) => (
                <div>
                  <Link
                    href={{
                      pathname: "/categories/[category]",
                      query: { category: `${element}` },
                    }}
                  >
                    {element}
                  </Link>
                </div>
              ))}
            </p>
          </div>
        </main>
        <footer className={styles.footer}>
          <a target="_blank" rel="noopener noreferrer">
            Powered by{" Kevin"}
            <span className={styles.logo}></span>
          </a>
        </footer>
      </Layout>
    </div>
  );
}
